### 1. Set up notebook and load data set

In [1]:
import numpy as np
data = np.loadtxt('mystery.dat',dtype='str')

In [2]:
DADA = np.zeros((1,101))
for row in data:
    row = row.split(',')
    row = [float(num) for num in row]
    DADA = np.vstack((DADA,row))

    
DADA = np.delete(DADA, 0, 0)    

In [3]:
x = DADA[:,0:100]
y = DADA[:,100]

### 2. Feature Engineering

**In this data set, $y$ is a linear function of just 10 of the features in , plus some noise. Your job is to identify those ten features.**

In [50]:
from sklearn.linear_model import Lasso
regr = Lasso(alpha = 0.55) 
regr.fit(x,y)
w = regr.coef_

print(w)

[ 0.          0.16683755  0.06929291  0.          0.35083895 -0.
  0.34002443 -0.         -0.         -0.          0.46438447 -0.
  0.29430879  0.         -0.         -0.          0.58932974 -0.
  0.42436172  0.          0.         -0.          0.44812406  0.         -0.
 -0.         -0.          0.          0.0345059   0.         -0.          0.
  0.         -0.         -0.         -0.         -0.          0.         -0.
  0.         -0.          0.         -0.         -0.          0.         -0.
 -0.         -0.          0.          0.         -0.          0.          0.
  0.         -0.          0.         -0.         -0.          0.          0.
  0.          0.          0.         -0.         -0.          0.         -0.
 -0.          0.          0.          0.          0.          0.          0.
  0.          0.         -0.          0.         -0.         -0.
  0.09835105 -0.         -0.         -0.         -0.         -0.         -0.
  0.         -0.         -0.          0.       

In [51]:
for i in w:
    if i != 0:
        print( np.where(w == i))

(array([1], dtype=int64),)
(array([2], dtype=int64),)
(array([4], dtype=int64),)
(array([6], dtype=int64),)
(array([10], dtype=int64),)
(array([12], dtype=int64),)
(array([16], dtype=int64),)
(array([18], dtype=int64),)
(array([22], dtype=int64),)
(array([28], dtype=int64),)
(array([80], dtype=int64),)
